In [5]:
import numpy as np
import pandas as pd
from numpy import array
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split,cross_val_score,cross_validate,GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, multilabel_confusion_matrix, classification_report

In [6]:
df = pd.read_csv('SpotifyWithDate.csv',encoding='latin-1')

# Normalize data
X, y = df.drop(columns=['popularity', 'track_id']), df['popularity']
X = (X-X.min())/(X.max()-X.min())
y = ((y-1)//20)+1

print(X)
print(y)

        danceability  instrumentalness  liveness  loudness  speechiness  \
0           0.821332          0.000000  0.048701  0.713030     0.048370   
1           0.798730          0.000503  0.079297  0.818937     0.023603   
2           0.639436          0.000108  0.041633  0.719526     0.026355   
3           0.608223          0.000001  0.039411  0.769941     0.005186   
4           0.530729          0.125125  0.100300  0.839360     0.012595   
...              ...               ...       ...       ...          ...   
143611      0.628673          0.000000  0.321438  0.813374     0.008150   
143612      0.360672          0.001792  0.136651  0.748332     0.150085   
143613      0.670649          0.000012  0.538538  0.820454     0.009208   
143614      0.781509          0.000025  0.053447  0.859996     0.388230   
143615      0.617910          0.000000  0.107368  0.789645     0.018628   

         valence      year  
0       0.265646  0.950820  
1       0.869155  0.934426  
2       0.73

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=5)

# Take about 10 mins to train the model
mlp = MLPClassifier(solver = 'sgd',activation="relu", hidden_layer_sizes=(19, 35), learning_rate_init=0.02, max_iter=400, random_state=4)
nn_model = mlp.fit(X_train, y_train)


In [33]:
# Make prediction
y_pred = nn_model.predict(X_test)

# Accuracy
print("\nAccuracy: ")
print(accuracy_score(y_test, y_pred))

# MSE
print('\nMSE: ')
print(mean_squared_error(y_test,y_pred))

# The map of label and their precision and recall
print("\nPrecision and recall:" )
print(classification_report(y_test, y_pred))


print("Confusion matrix: ")
matrix = confusion_matrix(y_test, y_pred)
multi_matrix = multilabel_confusion_matrix(y_test, y_pred)
print(multi_matrix)


Accuracy: 
0.48771034002553093

MSE: 
0.7187652315190902

Precision and recall:
              precision    recall  f1-score   support

           1       0.61      0.37      0.46     10255
           2       0.47      0.74      0.57     17745
           3       0.46      0.31      0.37     12089
           4       0.73      0.10      0.18      2840
           5       0.00      0.00      0.00       156

    accuracy                           0.49     43085
   macro avg       0.45      0.31      0.32     43085
weighted avg       0.51      0.49      0.46     43085

Confusion matrix: 
[[[30445  2385]
  [ 6454  3801]]

 [[10303 15037]
  [ 4626 13119]]

 [[26454  4542]
  [ 8289  3800]]

 [[40137   108]
  [ 2547   293]]

 [[42929     0]
  [  156     0]]]


C:\Users\Anna Feng\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anna Feng\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anna Feng\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
